// mockData/jobs.js
export const jobs = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Pune",
    seniority: "Junior",
    type: "Full Time",
    range: "5 LPA - 7 LPA",
    postedAgo: "2 days ago",
    suggested: true,
    recommended: true,
    remote: true,
    salaryBand: "5-7 LPA",
    country: "IN",
    description: "Work on modern frontend apps using React.",
    responsibilities: [
      "Build reusable UI components",
      "Collaborate with designers",
      "Write clean code",
    ],
  },
  {
    id: "2",
    title: "Backend Developer",
    company: "CodeFactory",
    location: "Bangalore",
    seniority: "Mid",
    type: "Full Time",
    range: "8 LPA - 12 LPA",
    postedAgo: "5 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "8-12 LPA",
    country: "IN",
    description: "Develop scalable backend systems.",
    responsibilities: [
      "Write REST APIs",
      "Database design",
      "Code optimization",
    ],
  },
  {
    id: "3",
    title: "Full Stack Engineer",
    company: "DevSolutions",
    location: "Mumbai",
    seniority: "Senior",
    type: "Contract",
    range: "12 LPA - 18 LPA",
    postedAgo: "1 week ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "12-18 LPA",
    country: "IN",
    description: "Work across backend and frontend technologies.",
    responsibilities: ["Develop APIs", "Integrate UI", "Cloud deployment"],
  },
  {
    id: "4",
    title: "UI/UX Designer",
    company: "PixelWorks",
    location: "Delhi",
    seniority: "Mid",
    type: "Full Time",
    range: "6 LPA - 9 LPA",
    postedAgo: "3 days ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "6-9 LPA",
    country: "IN",
    description: "Design modern, user-friendly interfaces.",
    responsibilities: [
      "Create wireframes",
      "Work with developers",
      "Conduct user research",
    ],
  },
  {
    id: "5",
    title: "React Native Developer",
    company: "Appify",
    location: "Remote",
    seniority: "Mid",
    type: "Full Time",
    range: "10 LPA - 14 LPA",
    postedAgo: "6 days ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "10-14 LPA",
    country: "IN",
    description: "Build cross-platform mobile apps.",
    responsibilities: [
      "Develop React Native apps",
      "Integrate APIs",
      "Maintain code quality",
    ],
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "CloudNet",
    location: "Hyderabad",
    seniority: "Senior",
    type: "Full Time",
    range: "15 LPA - 20 LPA",
    postedAgo: "4 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "15-20 LPA",
    country: "IN",
    description: "Automate CI/CD pipelines and cloud infra.",
    responsibilities: ["Manage AWS infra", "Setup CI/CD", "Monitor systems"],
  },
  {
    id: "7",
    title: "Data Scientist",
    company: "AI Labs",
    location: "Chennai",
    seniority: "Mid",
    type: "Full Time",
    range: "12 LPA - 16 LPA",
    postedAgo: "2 weeks ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "12-16 LPA",
    country: "IN",
    description: "Analyze data and build ML models.",
    responsibilities: [
      "Data cleaning",
      "Model building",
      "Deploy ML pipelines",
    ],
  },
  {
    id: "8",
    title: "QA Engineer",
    company: "SoftTest",
    location: "Noida",
    seniority: "Junior",
    type: "Full Time",
    range: "4 LPA - 6 LPA",
    postedAgo: "1 day ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "4-6 LPA",
    country: "IN",
    description: "Test and ensure product quality.",
    responsibilities: [
      "Write test cases",
      "Manual & automation testing",
      "Report bugs",
    ],
  },
  {
    id: "9",
    title: "System Administrator",
    company: "InfraTech",
    location: "Pune",
    seniority: "Mid",
    type: "Full Time",
    range: "7 LPA - 10 LPA",
    postedAgo: "8 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "7-10 LPA",
    country: "IN",
    description: "Maintain servers and internal infra.",
    responsibilities: [
      "Manage Linux servers",
      "Network setup",
      "Backup systems",
    ],
  },
  {
    id: "10",
    title: "AI Engineer",
    company: "NextGenAI",
    location: "Remote",
    seniority: "Senior",
    type: "Full Time",
    range: "20 LPA - 25 LPA",
    postedAgo: "3 weeks ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "20-25 LPA",
    country: "IN",
    description: "Develop cutting-edge AI solutions.",
    responsibilities: [
      "Experiment with models",
      "Work with TensorFlow",
      "Deploy AI APIs",
    ],
  },
  // ---------- Jobs 11 to 30 (newly added) ----------
  {
    id: "11",
    title: "Java Developer",
    company: "EnterpriseSoft",
    location: "Bangalore",
    seniority: "Mid",
    type: "Full Time",
    range: "8 LPA - 12 LPA",
    postedAgo: "2 days ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "8-12 LPA",
    country: "IN",
    description: "Develop enterprise Java applications.",
    responsibilities: ["Spring Boot", "REST APIs", "Database queries"],
  },
  {
    id: "12",
    title: "Python Developer",
    company: "PyWorks",
    location: "Hyderabad",
    seniority: "Mid",
    type: "Full Time",
    range: "10 LPA - 14 LPA",
    postedAgo: "5 days ago",
    suggested: false,
    recommended: true,
    remote: true,
    salaryBand: "10-14 LPA",
    country: "IN",
    description: "Develop Python backend and scripts.",
    responsibilities: ["Flask/Django", "Data pipelines", "Scripting"],
  },
  {
    id: "13",
    title: "Golang Developer",
    company: "GoTech",
    location: "Mumbai",
    seniority: "Mid",
    type: "Full Time",
    range: "12 LPA - 16 LPA",
    postedAgo: "1 week ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "12-16 LPA",
    country: "IN",
    description: "Work on backend systems in Go.",
    responsibilities: ["Build APIs", "Microservices", "Performance tuning"],
  },
  {
    id: "14",
    title: "C++ Developer",
    company: "FinSoft",
    location: "Delhi",
    seniority: "Senior",
    type: "Full Time",
    range: "18 LPA - 22 LPA",
    postedAgo: "6 days ago",
    suggested: true,
    recommended: false,
    remote: false,
    salaryBand: "18-22 LPA",
    country: "IN",
    description: "Develop trading and financial systems.",
    responsibilities: ["Low latency systems", "Multithreading", "Optimization"],
  },
  {
    id: "15",
    title: "PHP Developer",
    company: "WebSolutions",
    location: "Pune",
    seniority: "Junior",
    type: "Full Time",
    range: "5 LPA - 8 LPA",
    postedAgo: "3 days ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "5-8 LPA",
    country: "IN",
    description: "Build web apps using PHP & Laravel.",
    responsibilities: ["Write PHP code", "Integrate APIs", "Maintain MySQL DB"],
  },
  {
    id: "16",
    title: "Kotlin Android Developer",
    company: "AppMakers",
    location: "Remote",
    seniority: "Mid",
    type: "Full Time",
    range: "10 LPA - 15 LPA",
    postedAgo: "8 days ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "10-15 LPA",
    country: "IN",
    description: "Develop native Android apps using Kotlin.",
    responsibilities: ["Kotlin code", "Integrate APIs", "Unit testing"],
  },
  {
    id: "17",
    title: "Swift iOS Developer",
    company: "iTech",
    location: "Chennai",
    seniority: "Mid",
    type: "Full Time",
    range: "12 LPA - 18 LPA",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "12-18 LPA",
    country: "IN",
    description: "Build iOS apps using Swift.",
    responsibilities: ["Swift code", "UI development", "App store release"],
  },
  {
    id: "18",
    title: "Blockchain Developer",
    company: "CryptoSoft",
    location: "Remote",
    seniority: "Senior",
    type: "Full Time",
    range: "20 LPA - 30 LPA",
    postedAgo: "2 weeks ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "20-30 LPA",
    country: "IN",
    description: "Develop smart contracts and blockchain apps.",
    responsibilities: [
      "Solidity/Ethereum",
      "Smart contracts",
      "Blockchain APIs",
    ],
  },
  {
    id: "19",
    title: "Cybersecurity Analyst",
    company: "SecureIT",
    location: "Delhi",
    seniority: "Mid",
    type: "Full Time",
    range: "12 LPA - 16 LPA",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "12-16 LPA",
    country: "IN",
    description: "Secure networks and applications.",
    responsibilities: [
      "Security audits",
      "Penetration testing",
      "Incident response",
    ],
  },
  {
    id: "20",
    title: "Cloud Engineer",
    company: "CloudWorks",
    location: "Bangalore",
    seniority: "Senior",
    type: "Full Time",
    range: "15 LPA - 22 LPA",
    postedAgo: "3 weeks ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "15-22 LPA",
    country: "IN",
    description: "Work on cloud infra and services.",
    responsibilities: ["AWS/GCP/Azure", "Infra automation", "Monitoring"],
  },
  {
    id: "21",
    title: "Rust Developer",
    company: "FastCode",
    location: "Amsterdam",
    seniority: "Mid",
    type: "Full Time",
    range: "85k - 95k",
    postedAgo: "2 days ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "85k-95k",
    country: "NL",
    description: "Develop high-performance backend systems in Rust.",
    responsibilities: [
      "Write Rust code",
      "Optimize performance",
      "Code review",
    ],
  },
  {
    id: "22",
    title: "Machine Learning Engineer",
    company: "DeepAI",
    location: "Canada",
    seniority: "Senior",
    type: "Full Time",
    range: "120k - 140k",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "120k-140k",
    country: "CA",
    description: "Develop and deploy ML models at scale.",
    responsibilities: [
      "Build ML pipelines",
      "Experiment with models",
      "Deploy to cloud",
    ],
  },
  {
    id: "23",
    title: "Game Developer",
    company: "GameWorks",
    location: "Pune",
    seniority: "Junior",
    type: "Full Time",
    range: "6 LPA - 9 LPA",
    postedAgo: "4 days ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "6-9 LPA",
    country: "IN",
    description: "Develop 2D/3D games in Unity or Unreal.",
    responsibilities: ["Game mechanics", "Graphics", "Multiplayer"],
  },
  {
    id: "24",
    title: "Embedded Systems Engineer",
    company: "ChipTech",
    location: "Bangalore",
    seniority: "Mid",
    type: "Full Time",
    range: "10 LPA - 14 LPA",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "10-14 LPA",
    country: "IN",
    description: "Develop firmware for embedded systems.",
    responsibilities: ["C/C++ code", "Microcontrollers", "Testing"],
  },
  {
    id: "25",
    title: "Big Data Engineer",
    company: "DataStream",
    location: "Hyderabad",
    seniority: "Senior",
    type: "Full Time",
    range: "18 LPA - 24 LPA",
    postedAgo: "2 weeks ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "18-24 LPA",
    country: "IN",
    description: "Work on large-scale data processing.",
    responsibilities: ["Hadoop/Spark", "ETL pipelines", "Data lakes"],
  },
  {
    id: "26",
    title: "AR/VR Developer",
    company: "ImmersiTech",
    location: "Delhi",
    seniority: "Mid",
    type: "Full Time",
    range: "12 LPA - 16 LPA",
    postedAgo: "5 days ago",
    suggested: true,
    recommended: true,
    remote: false,
    salaryBand: "12-16 LPA",
    country: "IN",
    description: "Develop immersive AR/VR experiences.",
    responsibilities: ["Unity/Unreal", "3D modeling", "Optimization"],
  },
  {
    id: "27",
    title: "Site Reliability Engineer",
    company: "Uptime Inc",
    location: "Remote",
    seniority: "Senior",
    type: "Full Time",
    range: "20 LPA - 28 LPA",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: true,
    salaryBand: "20-28 LPA",
    country: "IN",
    description: "Ensure system reliability and uptime.",
    responsibilities: ["Monitoring", "Incident response", "Automation"],
  },
  {
    id: "28",
    title: "Product Manager",
    company: "BizTech",
    location: "Mumbai",
    seniority: "Senior",
    type: "Full Time",
    range: "25 LPA - 35 LPA",
    postedAgo: "2 weeks ago",
    suggested: true,
    recommended: false,
    remote: false,
    salaryBand: "25-35 LPA",
    country: "IN",
    description: "Drive product strategy and execution.",
    responsibilities: ["Roadmaps", "Stakeholder management", "Agile delivery"],
  },
  {
    id: "29",
    title: "Technical Writer",
    company: "DocuSoft",
    location: "Pune",
    seniority: "Junior",
    type: "Full Time",
    range: "4 LPA - 7 LPA",
    postedAgo: "3 days ago",
    suggested: true,
    recommended: true,
    remote: true,
    salaryBand: "4-7 LPA",
    country: "IN",
    description: "Write technical documentation and guides.",
    responsibilities: [
      "Write docs",
      "API documentation",
      "Work with engineers",
    ],
  },
  {
    id: "30",
    title: "Digital Marketing Specialist",
    company: "MarketPro",
    location: "Delhi",
    seniority: "Mid",
    type: "Full Time",
    range: "6 LPA - 10 LPA",
    postedAgo: "1 week ago",
    suggested: true,
    recommended: false,
    remote: false,
    salaryBand: "6-10 LPA",
    country: "IN",
    description: "Manage SEO/SEM and digital campaigns.",
    responsibilities: ["SEO/SEM", "Campaigns", "Analytics"],
  },
];
