export const jobs = [
  {
    id: "1",
    title: "Frontend Designer",
    company: "Info Corp",
    location: "New York",
    seniority: "Senior",
    type: "Full Time",
    range: "50k - 70k",
    postedAgo: "10 hours ago",
    suggested: true,
    recommended: false,
    remote: false,
    salaryBand: "80k-90k",
    country: "US",
    description:
      "Design and build UI components, collaborate with product and backend teams.",
    responsibilities: [
      "Build reusable components",
      "Work with designers",
      "Improve performance",
    ],
  },
  {
    id: "2",
    title: "Python Developer",
    company: "Code INC",
    location: "Germany",
    seniority: "Senior",
    type: "Full Time",
    range: "80k - 90k",
    postedAgo: "2 days ago",
    suggested: false,
    recommended: true,
    remote: true,
    salaryBand: "80k-90k",
    country: "DE",
    description:
      "Develop services and APIs in Python; write tests; code reviews.",
    responsibilities: ["Develop REST APIs", "Write unit tests", "Review PRs"],
  },
  {
    id: "3",
    title: "Product Engineer",
    company: "Cube Tech",
    location: "UK",
    seniority: "Senior",
    type: "Part Time",
    range: "—",
    postedAgo: "5 days ago",
    suggested: false,
    recommended: true,
    remote: true,
    salaryBand: "—",
    country: "UK",
    description: "Work closely with product to ship features end-to-end.",
    responsibilities: ["Own features", "Ship fast", "Collaborate"],
  },
  {
    id: "4",
    title: "React Native Developer",
    company: "MobileX",
    location: "San Francisco",
    seniority: "Mid",
    type: "Full Time",
    range: "90k - 110k",
    postedAgo: "1 day ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "90k-110k",
    country: "US",
    description:
      "Build cross-platform apps using React Native for Android and iOS.",
    responsibilities: ["Develop apps", "Debug issues", "Optimize performance"],
  },
  {
    id: "5",
    title: "Fullstack Engineer",
    company: "TechFusion",
    location: "India",
    seniority: "Senior",
    type: "Full Time",
    range: "30L - 40L",
    postedAgo: "3 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "30L-40L",
    country: "IN",
    description:
      "Develop and maintain full-stack applications with React and Node.js.",
    responsibilities: ["Frontend + Backend", "Database design", "Code reviews"],
  },
  {
    id: "6",
    title: "UI/UX Designer",
    company: "DesignHub",
    location: "Berlin",
    seniority: "Junior",
    type: "Contract",
    range: "40k - 50k",
    postedAgo: "1 week ago",
    suggested: false,
    recommended: true,
    remote: true,
    salaryBand: "40k-50k",
    country: "DE",
    description: "Design wireframes, mockups, and ensure good user experience.",
    responsibilities: ["Create wireframes", "Design mockups", "User testing"],
  },
  {
    id: "7",
    title: "Backend Developer",
    company: "ServerWorks",
    location: "Canada",
    seniority: "Senior",
    type: "Full Time",
    range: "70k - 90k",
    postedAgo: "4 hours ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "70k-90k",
    country: "CA",
    description: "Build scalable backend systems with Node.js and databases.",
    responsibilities: [
      "API Development",
      "Database management",
      "Optimize queries",
    ],
  },
  {
    id: "8",
    title: "Data Scientist",
    company: "DataCore",
    location: "UK",
    seniority: "Senior",
    type: "Full Time",
    range: "100k - 120k",
    postedAgo: "2 weeks ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "100k-120k",
    country: "UK",
    description: "Analyze datasets, build ML models, and deliver insights.",
    responsibilities: ["Build ML models", "Data cleaning", "Visualization"],
  },
  {
    id: "9",
    title: "Cloud Engineer",
    company: "SkyTech",
    location: "Australia",
    seniority: "Mid",
    type: "Full Time",
    range: "85k - 95k",
    postedAgo: "6 days ago",
    suggested: false,
    recommended: false,
    remote: true,
    salaryBand: "85k-95k",
    country: "AU",
    description: "Work with AWS, Azure, and GCP cloud infrastructures.",
    responsibilities: ["Manage cloud", "Deploy apps", "Monitor security"],
  },
  {
    id: "10",
    title: "DevOps Engineer",
    company: "Opsify",
    location: "Singapore",
    seniority: "Senior",
    type: "Full Time",
    range: "120k - 140k",
    postedAgo: "12 hours ago",
    suggested: true,
    recommended: false,
    remote: false,
    salaryBand: "120k-140k",
    country: "SG",
    description: "Automate CI/CD pipelines and manage infra deployments.",
    responsibilities: ["Setup CI/CD", "Monitor infra", "Improve reliability"],
  },
  {
    id: "11",
    title: "Java Developer",
    company: "CodeFactory",
    location: "India",
    seniority: "Junior",
    type: "Internship",
    range: "10k - 20k",
    postedAgo: "1 month ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "10k-20k",
    country: "IN",
    description: "Assist in developing Java-based enterprise solutions.",
    responsibilities: ["Write Java code", "Assist seniors", "Testing"],
  },
  {
    id: "12",
    title: "Android Developer",
    company: "AppWorld",
    location: "London",
    seniority: "Mid",
    type: "Full Time",
    range: "60k - 80k",
    postedAgo: "9 days ago",
    suggested: false,
    recommended: false,
    remote: true,
    salaryBand: "60k-80k",
    country: "UK",
    description: "Develop Android apps and publish to Play Store.",
    responsibilities: ["Build apps", "Fix bugs", "Integrate APIs"],
  },
  {
    id: "13",
    title: "iOS Developer",
    company: "AppleSoft",
    location: "California",
    seniority: "Senior",
    type: "Full Time",
    range: "100k - 130k",
    postedAgo: "2 days ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "100k-130k",
    country: "US",
    description: "Develop native iOS apps with Swift.",
    responsibilities: ["Develop iOS apps", "Test apps", "Optimize UI"],
  },
  {
    id: "14",
    title: "Blockchain Engineer",
    company: "CryptoTech",
    location: "Dubai",
    seniority: "Senior",
    type: "Full Time",
    range: "150k - 170k",
    postedAgo: "3 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "150k-170k",
    country: "AE",
    description: "Develop smart contracts and blockchain applications.",
    responsibilities: [
      "Write smart contracts",
      "Test DApps",
      "Security audits",
    ],
  },
  {
    id: "15",
    title: "Game Developer",
    company: "FunGames",
    location: "Japan",
    seniority: "Mid",
    type: "Full Time",
    range: "70k - 85k",
    postedAgo: "4 weeks ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "70k-85k",
    country: "JP",
    description: "Develop 2D and 3D games using Unity/Unreal.",
    responsibilities: ["Game dev", "Graphics integration", "Bug fixing"],
  },
  {
    id: "16",
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "US",
    seniority: "Senior",
    type: "Full Time",
    range: "110k - 130k",
    postedAgo: "15 days ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "110k-130k",
    country: "US",
    description: "Monitor systems and prevent cyber threats.",
    responsibilities: [
      "Threat analysis",
      "Incident response",
      "System hardening",
    ],
  },
  {
    id: "17",
    title: "AI Engineer",
    company: "NeuralWorks",
    location: "France",
    seniority: "Senior",
    type: "Full Time",
    range: "120k - 150k",
    postedAgo: "7 hours ago",
    suggested: true,
    recommended: false,
    remote: true,
    salaryBand: "120k-150k",
    country: "FR",
    description: "Build AI models for NLP and CV tasks.",
    responsibilities: ["Train models", "Deploy models", "Optimize performance"],
  },
  {
    id: "18",
    title: "Web Designer",
    company: "Creative Studio",
    location: "Spain",
    seniority: "Junior",
    type: "Part Time",
    range: "25k - 35k",
    postedAgo: "8 days ago",
    suggested: false,
    recommended: false,
    remote: true,
    salaryBand: "25k-35k",
    country: "ES",
    description: "Design websites and landing pages.",
    responsibilities: [
      "Design layouts",
      "Pick color schemes",
      "Basic HTML/CSS",
    ],
  },
  {
    id: "19",
    title: "Systems Engineer",
    company: "CoreSys",
    location: "Brazil",
    seniority: "Mid",
    type: "Full Time",
    range: "60k - 75k",
    postedAgo: "6 days ago",
    suggested: false,
    recommended: true,
    remote: false,
    salaryBand: "60k-75k",
    country: "BR",
    description: "Maintain IT infrastructure and system reliability.",
    responsibilities: [
      "System upgrades",
      "Monitor servers",
      "Troubleshoot issues",
    ],
  },
  {
    id: "20",
    title: "QA Engineer",
    company: "TestPro",
    location: "Poland",
    seniority: "Junior",
    type: "Full Time",
    range: "40k - 55k",
    postedAgo: "5 days ago",
    suggested: false,
    recommended: false,
    remote: true,
    salaryBand: "40k-55k",
    country: "PL",
    description: "Write and execute test cases for web and mobile apps.",
    responsibilities: ["Manual testing", "Automation testing", "Report bugs"],
  },
];
